
name: run main.py

on:
  schedule:
    - cron: '0 0-23/8 * * 1-5' # At minute 0 past every 8th hour from 0 through 23 on every day-of-week from Monday through Friday
  pull_request:
    branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: setup python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          SCOPE1 : ${{ vars.SCOPE1}}
          SAMPLE_SPREADSHEET_ID : ${{ secrets.SAMPLE_SPREADSHEET_ID}}
          SAMPLE_RANGE_NAME : ${{ vars.SAMPLE_RANGE_NAME}}
          X_CG_DEMO_API_KEY : ${{ secrets.X_CG_DEMO_API_KEY}}
          JSON_TOKEN : ${{ secrets.JSON_TOKEN}}
          JSON_CREDENTIALS : ${{ secrets.JSON_CREDENTIALS}}
        run: python main.py
